### ISSUE TITLE
Catch when a user forgets to call a method

### ISSUE THREAD

**Issue by oTree-org** [dmulholl/ibis#11]
For people migrating from Django templates, or a previous version of Ibis, a common problem would be templates that contain method calls without parentheses, e.g. {{ obj.some_method }}. It would be nice to catch this, especially since if you output it with `{{ }}`, it will produce text with angle brackets, which will be interpreted by the browser as HTML tags and produce confusing output:

```
<bound method A.m of <__main__.A object at 0x019F3990>>
```

Inside template tags, it will often fail silently (e.g. `{% if obj.my_method == 1 %}` will return false).

How about if we add this to `_resolve_variable`, after `if self.is_func_call:`:

```
        elif isinstance(obj, types.MethodType):
            msg = f"'{self.varstring}' is a method, so you must add parentheses, like '{self.varstring}()' "
            msg += f"(template '{self.token.template_id}', line {self.token.line_number})."
            raise errors.TemplateRenderingError(msg, self.token)
```

It requires `import types` at the top. I checked with `python -X importtime` and this doesn't add any overhead (I guess `types` is already loaded with Python.)

**Comment by dmulholl** [comment]
There's actually no way to tell whether an uncalled function reference is an error or not. The user might want to print the function for debugging or pass it on to a filter to do something more complex with it. 

If we could be guaranteed that every uncalled function was an error we could just call it and then it wouldn't be an error any more :)

**Comment by oTree-org** [comment]
Hi, thanks for the response. I'm OK keeping the behavior as is, or taking a "wait and see" approach. However, I want to share my experience that while migrating from django was generally a smooth process, this was quite challenging.

(Hopefully many people will be migrating from Django to Ibis soon, so I want to bring this to your attention ;))

The reason is you have to manually look at every expression in your templates and see if they contain implicit method calls. There are many variations so it's not something you can grep through.

For example:

```
{{ p.get_name }} ## outputs `>` because the the real output `<bound method A.m of <__main__.A object at 0x019F3990>>` is swallowed by the HTML renderer
{% if user.is_admin %}  ## always True
{% if project.owner.num_projects == 0 %}  ## always False
{% for x in player.in_all_rounds %}...{% endfor %}  ## iterating a method fails silently, even though I am in Strict mode.
```

Sometimes it's a bit hard to determine whether something is a method, especially with chained lookups and 3rd party packages.

(Just to be clear, I was just referring to checking for methods, not necessarily all callables, since I think it's with methods that the majority of these problems will occur.)

You are right that we can't guarantee that an uncalled function reference is an error. Sometimes people might want to legitimately use an uncalled method in a template. But in that case, they would get an error message saying that doing this is not supported by Ibis templates, just as various other things are not supported. They can probably easily find another way to accomplish their goal. I think forbidding code constructs that commonly lead to errors is a good feature to have.
To me it seems better to be restrictive at first and only enable it later if users express a need for that.

> The user might want to print the function for debugging 

Then they write `{{ foo.bar }}`, and when they reload they get an error page saying `foo.bar is a method...`, so they get their answer ;) There is not much else you can see about a method from its __str__, so this type of introspective debugging is better done with print statements etc. And doing this was not possible in Ibis 1.x so there is no regression in functionality.

> or pass it on to a filter to do something more complex with it.

IMO that sounds like a questionable thing to be doing inside a template.

> If we could be guaranteed that every uncalled function was an error we could just call it and then it wouldn't be an error any more :)

I see your point, but that is not a solution, as demonstrated by the previous bug about ``__call__``. We cannot auto-call everything that is callable, since you have regular objects like wtforms that define `__call__`. (You could say that we should auto-call regular functions and methods but not objects with `__call__`, but that creates complexity.)

Anyway as I said I am OK keeping the current behavior, but want to raise this to your attention in case easing the migration from Django becomes a focus for the project. I am sure there are many people who want to move their projects from Django to a more modern framework like Starlette or FastAPI. It seems like many of those frameworks recommend Jinja as their templating system but I think Ibis would be a better choice for many projects :)
