### ISSUE TITLE
Support for non-English formatting

### ISSUE THREAD

**Issue by oTree-org** [dmulholl/ibis#12]
Numbers, dates, times, etc. are written differently in different languages., e.g. a comma decimal separator (`3,14`). How about some minimal hook to allow applications to format values according to the locale? Here is a suggestion. In `ibis/__init__.py`, add some function that can be patched (just as the global loader can be patched):

```
def localize(value):
    return str(value)
```

Then in PrintNode.wrender, instead of `str(content)` we do:

        content = ibis.localize(content)

**Comment by dmulholl** [comment]
I think this is a better use-case for a filter - you can register a custom filter to format any value in any way you like.

**Comment by oTree-org** [comment]
OK Seems reasonable to me :)
