### ISSUE TITLE
Passing arguments to {% include %}

### ISSUE THREAD

**Issue by oTree-org** [dmulholl/ibis#15]
Often I want to include the same template in a page multiple times, but passing different arguments. This is a handy way to make reusable components. In Django it would be like this:

          {% include 'includes/payment_table.html' with rows=participants_not_reviewed reviewable=True %}
          ...some content goes here...
          {% include 'includes/payment_table.html' with rows=participants_reviewed reviewable=False %}

The best way I have found to do so in Ibis is like this:

          {% with reviewable=True %}
            {% with participants=participants_not_reviewed %}
              {% include 'includes/payment_table.html' %}
            {% endwith %}
          {% endwith %}
          ...some content goes here...
          {% with reviewable=False %}
            {% with participants=participants_reviewed %}
              {% include 'includes/payment_table.html' %}
            {% endwith %}
          {% endwith %}

It's not that bad, but what do you think of some friendlier syntax? Either the ability to pass arguments to {% include %} or pass multiple arguments to {% with %}.

**Comment by dmulholl** [comment]
That's a really good idea, I've never considered the use-case of passing arguments to an included template.

The only hard part about implementing it would be matching on the argument separator as Ibis doesn't currently use a proper recursive expression parser, just a bunch of regular expressions. I'm tempted to add one and if I do I'll definitely add support for for multiple arguments to both the `include` and `with` tags.

In the meantime, you could register a custom `include` tag to override the default one. If you know the use-case is limited it wouldn't need to be robust and you could just match on spaces or commas.

**Comment by oTree-org** [comment]
Ok thank you!

**Comment by dmulholl** [comment]
Turns out there was a simple solution after all. In v3.2.0 the `with` and `include` tags now support multiple variable declarations separated by `&` symbols:

    {% include "template" with foo = True & bar = 123 %}

    {% with foo = get_foo() & bar = get_bar() %}
        ...
    {% endwith %}

**Comment by oTree-org** [comment]
That looks great, thank you!
