### ISSUE TITLE
"verbatim" tag

### ISSUE THREAD

**Issue by oTree-org** [dmulholl/ibis#16]
What do you think of having a "{% verbatim %}" tag like in Django? https://docs.djangoproject.com/en/3.2/ref/templates/builtins/#verbatim

This would allow easier integration with various JS frameworks like Vue, Handlebars, etc.

**Comment by oTree-org** [comment]
(If you consider it to be out of scope for Ibis, any hints how I can implement verbatim myself?)

**Comment by dmulholl** [comment]
Sorry, I missed this completely!

This would actually be a little tricky to implement - I think you'd have to bake it directly into the lexer or invalid template markup inside verbatim tags would result in errors. It would have to work more like skipping over a template comment than parsing a regular instruction tag. (To be robust, you might also have to maintain a little stack or count of potentially nested verbatim tags so you could identify the correct end tag.)

I'll take a look when I get a chance and have a think about the best way to implement this.

**Comment by oTree-org** [comment]
Thanks for the reply! Actually it's a fairly minor issue; i am OK without it for now. I can see it would be complex to implement.
