### ISSUE TITLE
Formatting numbers?

### ISSUE THREAD

**Issue by joelthelion** [dmulholl/ibis#18]
I'm trying to round a floating point number to two decimal places. For example:

```
a = 3.1415
Template(""" hello {{ "%.2f" % a }} """).render({"a": a})
```

Needless to say, that doesn't work. I've tried a few options, but I'm at loss. I feel this is simple enough that there must be a solution. What am I missing?

Thanks!

**Comment by dmulholl** [comment]
Hi Joel. There's no built-in mechanism for rounding numbers but as @oTree-org says you can use a custom filter to do any kind of formatting you like. You can find the documentation here: 

https://www.dmulholl.com/docs/ibis/master/extensions.html#custom-filters

**Comment by joelthelion** [comment]
Thanks a lot for the kind answer! Not sure how I missed that. Of course, it works perfectly now.

**Comment by dmulholl** [comment]
@joelthelion I've updated the documentation to hopefully make this facility a bit clearer:

https://www.dmulholl.com/docs/ibis/master/extensions.html#custom-filters

Thanks for the feedback!
