### ISSUE TITLE
Add support off multiple directories into FileLoader

### ISSUE THREAD

**Issue by umanamente** [dmulholl/ibis#19]
Sometimes templates are located in multiple directories. FileLoader should search in multiple paths.

**Comment by dmulholl** [comment]
Thanks @umanamente and @oTree-org. I've added support for multiple base directories in `v3.3.0`, e.g.

~~~python
ibis.loader = ibis.loaders.FileLoader(
    '/path/to/base/dir1',
    '/path/to/base/dir2',
)
~~~
