### ISSUE TITLE
Option to remove empty lines where tags were

### ISSUE THREAD

**Issue by umanamente** [dmulholl/ibis#20]
The following code
```
    {% for post in posts %}
        <li>...</li>
    {% endfor %}
```
will produce empty lines where the tags were:
```
<li>...</li>

<li>...</li>

<li>...</li>
```
Jinja2 has switches to remove empty lines from the final rendered content. It would be nice to have in ibis

**Comment by dmulholl** [comment]
Sorry, whitespace formatting is out-of-scope for this tool -- it's very fiddly to implement well. I'm leaving this use-case to `jinja` 🙂
