### ISSUE TITLE
"Walrus operator" is not compatible with Python 3.7 

### ISSUE THREAD

**Issue by oTree-org** [dmulholl/ibis#5]
in nodes.py line 181, there is an assignment expression:

            if (token := self.token):

I wonder if this could be changed to a regular assignment, to keep compat with Python 3.7 and below?

            token = self.token
            if token:

**Comment by dmulholl** [comment]
That's my favourite operator!

I guess I can struggle along without it though. I've dropped the required Python version to 3.6 which I think is the lowest version to support f-strings. Now those I couldn't live without.
