### ISSUE TITLE
{{ item.0 }} lookups and |index filter

### ISSUE THREAD

**Issue by oTree-org** [dmulholl/ibis#7]
One commonly used feature in Django templates is number-based lookups, e.g. `{{ item.0 }}`, `{{ item.1 }}`. These are typically used for small tuples passed to the template, such as `(value, label)`, `(min, max)`, `(current, total)`, etc.

Ibis has the |index filter, but it actually works inversely to Python's `.index()` method:

```
arr = [1,2,3]
print(T('{{ arr|index(2) }}').render(arr=arr))
print(arr.index(2))
```

Outputs:

```
3
1
```

(I guess Python should have called the method `indexof` to avoid the ambiguity.)

What do you think of supporting dot-lookup notation, such as ``{{ item.0 }}`? 

I think this could be implemented by adding the following to Context.resolve:

	if word.isdigit():
	    result = result[int(word)]
	else:
		...

(Possible errors include IndexError if the index is out of range, and TypeError if the item is not subscriptable.)

**Comment by dmulholl** [comment]
Implemented in the latest release!

**Comment by oTree-org** [comment]
Nice, thanks!
