### ISSUE TITLE
Method calls inside expressions: {{ a.b().c }}

### ISSUE THREAD

**Issue by oTree-org** [dmulholl/ibis#8]
Now that parentheses are required explicitly, {{ a.b.c }} no longer works when `b` is a method. For example:

```
class Boss:
    decision = 'accept'

b = Boss()

class Player:
    def get_boss(self): return b

res = Template('{{ player.get_boss().decision }}').render(player=Player(), strict_mode=True)
```

Raises:

```ibis.errors.UndefinedVariable: Cannot resolve the variable 'player.get_boss()' in template 'UNIDENTIFIED', line 1.```

**Comment by dmulholl** [comment]
This is actually working as intended - function calls have only ever been supported at the end of the variable chain.

It isn't possible to support chained function calls given the current architecture but you can use a `with` block to achieve the same end:

    {% with boss = player.get_boss() %}
        {{ bos.decision }}
    {% endwith %}
