### ISSUE TITLE
Certain variable names cannot be used: update, push, template, etc

### ISSUE THREAD

**Issue by oTree-org** [dmulholl/ibis#9]
```
res = T('{{ update }}').render(update='you have 1 new message')

print(res)
```

Output:

`<bound method Context.update of <ibis.context.Context object at 0x02E838F0>>`

As you can see, using any name that is also an attribute of the Context object results in that variable name getting shadowed.

**Comment by dmulholl** [comment]
Ha, nice catch. I broke this when I reordered attribute lookups in the `.resolve()` method. Fixed now on `master`. Thanks!
